### PR TITLE
Update unidata-gen.el

### PR DESCRIPTION
**Pull request by hyphenlee**
something wrong with the new code that can't compile

### CODE REVIEW

**Comment by jwiegley** [comment]
@hyphenlee This patch is too large to be considered. Is some kind of rebasing going on?

**Comment by dgutov** [comment]
@jwiegley Apparently both pull requests here are based on the old Git export of the Bazaar repository.

The best we could do is to just close them.

**Comment by jwiegley** [comment]
@dgutov Agreed, but I do not control this account.

**Comment by hyphenlee** [comment]
@jwiegley I don't know what's happened here. I got compile error with previous version, and I just edit 5 lines to make it work. I think it doesn't matter now. Maybe just discard it.

**Pull request closed without merging**
